config/routes.rb
MicroWebsite::Application.routes.draw do

  devise_for :users, :controllers => { :passwords => "passwords" , :registrations => "registrations",:sessions=>'sessions'} do
    get "change", :to => "devise/registrations#edit"
    get "change_password", :to => "devise/passwords#change"
    get "signin", :to => "devise/sessions#new"
    get "signup", :to => "devise/registrations#new"
    get "signout", :to => "devise/sessions#destroy"
  end

  get "user/manage/:type", :to=>"users#index"
  post "user/disable/:uid", :to=>"users#disable"
  post "user/enable/:uid", :to=>"users#enable"
  get "user/delete/:uid", :to=>"users#delete"
  match 'obtain_award', :to=>'awards#obtain_award' ,via: 'get'
  match 'obtain_qr_code_award', :to=>'qr_code_awards#obtain_award' ,via: 'get'
  post "site/verify/:sid",:to=>"sites#verify"
  post "site/change_status/:sid/:status",:to=>"sites#change_status"
  match "/sites/static", :to => "pages#static"
  match '/destroy_site' ,:to=>'sites#destroy_site' ,via: 'get'
  match "/sites/:site_id/pages/preview", :to => "pages#preview", :as => "preview"
  match "/sites/:site_id/pages/form_preview", :to => "pages#form_preview", :as => "form_preview"
  match "/get_token", :to => "pages#get_token", :as => "get_token", via: 'get'
  match "/get_award_url", :to => "awards#get_award_url", :as => "get_award_url", via: 'get'
  match "/record_award", :to => "awards#record_award", :as => "record_award", via: 'post'
  match "/check_if_watch", :to => "awards#check_if_watch", :as => "check_if_watch", via: 'get'
  match '/check_zip' ,to: 'resources#is_not_repeat' ,via: 'get'
  match '/change_status' ,to: 'sites#change_each_status' ,via: 'get'
  match '/allimg' ,to: 'resources#allimage' ,via: 'get'
  match 'image_text_page' ,to: 'image_streams#create_imgtxt' , via: 'post'
  match 'imgtxt_edit_update' ,to: 'image_streams#edit_update' ,via: 'post'
  match '/delete_post' ,to: 'posts#delete_post' ,via: 'get'
  match '/top' ,to: 'posts#top' ,via: 'get'
  match '/untop' ,to: 'posts#untop' ,via: 'get'
  match '/search_sites' ,to: 'sites#search',via: 'get'
  match '/model_page' ,to: 'pages#model_page',via: 'post'
  match '/sites/:site_id/app_managements/get_form_date' => 'app_managements#get_form_date', :as => :preview_visits, :via => :post
  match '/submit_redirect' => 'app_managements#submit_redirect', :as => :submit_redirect, :via => :get
  match '/get_form_date' => 'client_forms#get_form_date', :as => :preview_visits, :via => :post
  match '/get_qr_image' ,to:"weixins#get_qr_image"
  match '/get_qr_img_by_url' ,to:"weixins#get_qr_img_by_url"
  match '/dispose_award' ,to:"weixins#dispose_award"
  # Sample resource route with options:
  namespace :api do
    resources :clients do
      collection do
        post :login, :message_detail, :refresh, :del_recent_client, :get_token
        post :edit_client, :set_receive, :set_undisturbed
      end
    end
    resources :messages do
      collection do
        post :make_record, :edit_record, :send_message_to_user
      end
    end
  end
  resources  :weixins do
    member do
      get :get_qr_image
    end
  end
  resources :sites do
    member do
      post :verify_site
    end
    resources :micro_messages 
    resources :micro_imgtexts
    resources :weixin_replies
    resources :app_managements do
      collection do        
        post :create_client_info_model

      end
    end
    resources :qr_codes do
      collection do
        get :after_scan
      end
    end

    resources :qr_code_awards  do
      get :win_award_info
    end

    resources :awards do
      get :win_award_info
      collection do
        get :template
        post :save_template
      end
      member do
        get :change
      end
    end
    resources :posts do
      collection do
        get :bbs, :see_more

      end
      member do
        get :bbs_detail,:star
      end
      resources :replies do
        collection do
          get :see_more
        end
        member do
          get :verifyt,:verifyf,:verify
        end
      end
    end
    
    resources :resources
    resources :pages do
      resources :form_datas
      collection do
        get :sub, :form, :style, :sub_new,  :form_new ,:tmlt_sub_new,:change
        post :preview, :save_template3,:tmlt_sub_create,:zdy_sub_create
      end
      member do
        get :sub_edit,:form_edit, :if_authenticate, :sub_preview ,:tmlt_sub_edit
        post :submit_queries,:tmlt_sub_update
      end
    end
    
    resources :forms do
      member do
        get :submit_redirect
      end
    end

    resources :image_streams do
      #对集合进行操作
      collection do
        get :img_stream
      end
      #对单个进行操作
      member do
        get :edit_itpage,:change
      end
    end
    resources :image_texts do
      collection do
        post :preview
      end
      member do
        put :it_preview
        get :change
      end
    end
    resources :reminds do
      collection do
        post :create_records,:message_record
      end
      member do
      end
    end
  end
  match "/weixins/accept_token" => "weixins#accept_token"

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  devise_scope :user do
    root to: "devise/sessions#new"
  end

  # See how all your routes lay out with "rake routes"


  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
  # match '/:path_name',:to => "pages#static", :path_name => /\w+\/.+\.html/
end

app/controllers/image_streams_controller.rb
#encoding:utf-8
class ImageStreamsController < ApplicationController
  require 'will_paginate/array'
  before_filter :get_site
  SITE_PATH = "/public/allsites/%s/"
  PUBLIC_PATH =  Rails.root.to_s + "/public/allsites"
  layout 'sites'
  def new
    @site=Site.find(params[:site_id])
    #@imgs_path=@site.resources
    #@imgs_path =@site.resources.paginate(:page=>params[:page],:per_page=>12,:conditions =>"path_name like '%.jpg' or path_name like '%.gif' or path_name like '%.png' or path_name like '%.jpeg' ")
    @imgs_pathes = @site.resources.where("path_name like '%.jpg' or path_name like '%.gif' or path_name like '%.png' or path_name like '%.jpeg' ")
    @imgs_path = @imgs_pathes.paginate(:page =>1,:per_page=>12)
    

  end

  def img_stream
    @site=Site.find(params[:site_id])
    @image_stream_pages=@site.pages.image_stream.paginate(page:params[:page]|| 1,:per_page => 10)
    #@imgs_path=@site.resources
  end
  def create_imgtxt
    name=params[:name];
    title=params[:title];
    check=params[:check];
    imgarr=params[:src].split(",");
    textstr=params[:pic_text] ;
    p imgarr,textstr
    @site=Site.find(params[:site_id]);
    @page=@site.pages.build
    @page.title=title
    @page.file_name=name+".html"
    @page.authenticate=check
    @page.types=5
    @page.path_name="/"+@site.root_path+"/"+name+".html"
    if @page.save
      page_image=@page.page_image_texts.build
      page_image.img_path=imgarr
      page_image.content=textstr
      page_image.save
      bag_img_magick imgarr
      content=get_content(imgarr,textstr)
      bigcontent=get_bigcontent(imgarr,textstr)
      save_in_file(content,bigcontent,@site,@page.file_name)
      render :text=>1
    else
      render :text=>0
    end
  end
  #截取图片
  def bag_img_magick(imgarr)
     #图片      
      imgarr.each do |x|
        filename=x.split("/")[-1]
        dirpath=Rails.root.to_s + "/public#{x.split('/')[0...-1].join('/')}"
        min_image(Rails.root.to_s + "/public#{x}",filename,dirpath)
      end
  end
 #资源全路径,文件名 ,dir
  def min_image(ful_path,filename,ful_dir)
    target_path=ful_dir+"/"+filename.split(".")[0...-1].join(".")+"_min."+filename.split(".")[-1]
    if !File.exist?(target_path)&&which_res(filename)=='img'
    image = MiniMagick::Image.open(ful_path)
    resize = 280 > image["width"] ? image["width"] : 280
    image.resize resize
    image.write  ful_dir+"/"+filename.split(".")[0...-1].join(".")+"_min."+filename.split(".")[-1]
    end
  end
  #删除图文页
  def destroy
    @site=Site.find(params[:site_id])
    Page.transaction do
      @page = Page.find(params[:id])
      if @page.destroy
        bigimg_path=PUBLIC_PATH+"/"+@site.root_path+"/bigimg_"+@page.file_name
        File.delete PUBLIC_PATH + @page.path_name if File.exists?(PUBLIC_PATH + @page.path_name)
        File.delete  bigimg_path if File.exists?(bigimg_path)
        flash[:success]='删除成功！'
        redirect_to img_stream_site_image_streams_path(@site)
      else
        flash[:success]='删除shibai ！'
        render 'img_stream'
      end
    end

  end
  
  def edit
    @page = Page.find(params[:id])
    @image_text =PageImageText.find_by_page_id(params[:id])
    @site=Site.find(params[:site_id])
    @imgs_pathes = @site.resources.where("path_name like '%.jpg' or path_name like '%.gif' or path_name like '%.png' or path_name like '%.jpeg' ")
    @imgs_path = @imgs_pathes.paginate(:page =>1,:per_page=>12)
  end
 
  def edit_update
    name=params[:name]+".html";
    title=params[:title];
    #check=params[:check];
    imgarr=params[:src].split(",");
    textstr=params[:pic_text];
    @site=Site.find(params[:site_id]);
    @page=Page.find(params[:id]);
    @image_text=PageImageText.find_by_page_id(params[:id])
    if @page.update_attributes(file_name:name,title:title)
      @image_text.update_attributes(img_path:imgarr,content:textstr)
      # 删除已经存在的html文件
      bigimg_path=PUBLIC_PATH+"/"+@site.root_path+"/bigimg_"+@page.file_name
      File.delete PUBLIC_PATH + @page.path_name if File.exists?(PUBLIC_PATH + @page.path_name)
      File.delete  bigimg_path if File.exists?(bigimg_path)
      #保存更新完的文件
      bag_img_magick imgarr
      content=get_content(imgarr,textstr)
      bigcontent=get_bigcontent(imgarr,textstr)
      save_in_file(content,bigcontent,@site,@page.file_name)
      render :text=>1
    else
      render :text=>0
    #  redirect_to site_image_texts_path(@site)
   # else
     # render "edit_itpage"
    end
  end
  
  #私有方法|||||||||||||||||||||||||||||||||||||||||||||||---------华丽的分割线----------||||||||||||||||||||||||||||||||||||||||||||||
  private
  #
  def which_res(name)
    @img_resources=%w[jpg png gif jpeg]
    @voice_resources=%w[mp3]
    @video_resoures=%w[mp4 avi rm rmvb]
    name=name.split('.')[-1]
    name.downcase!
    if @img_resources.include?(name)
      return 'img'
    elsif @voice_resources.include?(name)
      return 'voice'
    else @video_resoures.include?(name)
      return 'voide'
    end
  end
  #保存进
  def save_in_file(content,bigcontent,site,fname)
    site_path = Rails.root.to_s + SITE_PATH % site.root_path
    FileUtils.mkdir_p(site_path) unless Dir.exists?(site_path)
    FileUtils.rm site_path + fname if File::exist?(site_path + fname)
    File.open(site_path + fname, "wb") do |f|
      f.write(content.html_safe)
    end
    FileUtils.rm site_path + "bigimg_"+fname if File::exist?(site_path + "bigimg_"+fname)
    File.open(site_path + "bigimg_"+fname, "wb") do |fb|
      fb.write(bigcontent.html_safe)
    end
  end
  def encoding_character(str)
    arr={"<"=>"&lt;",">"=>"&gt;"}
    str.gsub(/<|>/){|s| arr[s]}
  end
  #得到内容
  def get_content(imgarr,textarr)
    str=""
    (0..imgarr.length-1).each do |x|
      p1=(textarr[x].nil? ? '':"<p>#{encoding_character textarr[x]}</p>")
      #image = MiniMagick::Image.open(Rails.root.to_s + '/public' +deal_img_to_min(imgarr[x]))
      #<li><a href='bigimg_#{@page.file_name}#page-#{x+1}'><img src='#{deal_img_to_min imgarr[x]}' width='140' height='#{image['height']*140/image['width']}' ></a>#{p1}</li>
      str+="<li><a href='bigimg_#{@page.file_name}#page-#{x+1}'><img  src='#{deal_img_to_min imgarr[x]}'></a>#{p1}</li>
      "
    end
    
#html 内容
    content="
    <!doctype html>
<html>
<head>
<meta charset='utf-8'>
<meta name='viewport' content='width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no'>
<title>#{@page.title}</title>
<script type='text/javascript' src='/allsites/js/jQuery-v1.9.0.js'></script>
<script type='text/javascript' src='/allsites/js/jquery.wookmark.js'></script>
<script type='text/javascript' src='/allsites/js/template_main.js'></script>

<link href='/allsites/style/template_style.css' rel='stylesheet' type='text/css'>
</head>

<body>
	<article>
         <section class='show_pic'>
         	  <ul>
                 #{str}
              </ul>
         </section>
    </article>
    " + page_footer(@site)+"
     <script type='text/javascript'>
    	$(function(){
			$('.show_pic ul li').wookmark({
				container:$('.show_pic ul'),
				offset:10,

			});
		})
    </script>
</body>
</html>
    "
    content
  end

  def get_bigcontent(imgarr,textarr)
    #<div class='text'>#{textarr[i-1]}</div>
    selection="";
    image=""
    (1..imgarr.length).each do|i|
      selection+="<section id='page-#{i}' data-role='page' class='demo-page'><div class=\'show_img si_#{i}\'></div></section>"
      image+=".si_#{i} { background: url('#{imgarr[i-1]}') no-repeat; background-size: cover;}
      "
    end
    bigcontent="
    <!doctype html>
<html>
<head>
<meta charset='utf-8'>
<meta name='viewport' content='width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no'>
<title>#{@page.title}</title>
<script type='text/javascript' src='/allsites/js/jQuery-v1.9.0.js'></script>
<script type='text/javascript' src='/allsites/js/jquery.mobile-1.3.2.js'></script>
<script type='text/javascript' src='/allsites/js/template_main.js'></script>

<link href='/allsites/style/jquery.mobile-1.3.2.css' rel='stylesheet' type='text/css'>
<link href='/allsites/style/template_style.css' rel='stylesheet' type='text/css'>
<style  type='text/css'>
#{image}
</style>
</head>
<body>
<article>
  <article>#{selection}</article>
</article>
" + page_footer(@site)+"
</body></html>"
  bigcontent
  end
end

app/views/image_streams/_add_imgstream.html.erb
<div style="height:100%;;padding:10px;background:white;">
	<div style="width:100%;margin-bottom: 5px ;text-align: center;">
		<h1  > 添加图片流页
		<br/>
		标题：<span class="check">*</span>
		<input type="text" id="title"/>
		文件名：<span class="check">*</span>
		<input type="text" id="name"/>.html
		</h1>
		访问权限：是
		<input type="radio" value=1 name="w" />
		否
		<input type="radio" value=0 name="w" checked/>
	</div>
	<div id="trashdiv" style="float:left;width:51%;height:450px;padding:0%;overflow: auto;">
		<div id="trash" class="ui-widget-content ui-state-default"style="margin:0px 35px;width:420px;background:white;float:right;">
			<h4 class="ui-widget-header"><span class="ui-icon ui-icon-folder-collapsed">Document</span> 您的图片区 <img src="/assets/add.png" alt="添加空白区域" onclick="add()" style="position: relative;left:322px;cursor:pointer;"/></h4>
			<ul class='gallery ui-helper-reset' id="trashh" >
			<li  class="ui-widget-content ui-corner-tr" style='width: 186px;' >
				<div style="height:144px;" >
				<img  src="/assets/temp.jpg" style="width:182px;height:144px; "/>
				</div>
				<a  title="Delete this image" onclick="delete_ele(this)"  class="ui-icon ui-icon-trash">Delete image</a>
				<textarea></textarea>
				<input type="hidden" name="temp_picture" />
			</li>
			<li  class="ui-widget-content ui-corner-tr" style='width: 186px;' >
				<div style="height:144px;" >
				<img  src="/assets/temp.jpg" style="width:182px;height:144px; "/>
				</div>
				<a  title="Delete this image" onclick="delete_ele(this)" class="ui-icon ui-icon-trash">Delete image</a>
				<textarea></textarea>
				<input type="hidden" name="temp_picture" />
			</li>
			<li  class="ui-widget-content ui-corner-tr" style='width: 186px;'>
				<div style="height:144px;" >
				<img  src="/assets/temp.jpg" style="width:182px;height:144px; "/>
				</div>
				<a  title="Delete this image" onclick="delete_ele(this)"  class="ui-icon ui-icon-trash">Delete image</a>
				<textarea></textarea>
				<input type="hidden" name="temp_picture" />
			</li>
			<li  class="ui-widget-content ui-corner-tr" style='width: 186px;'>
				<div style="height:144px;" >
				<img  src="/assets/temp.jpg" style="width:182px;height:144px; "/>
				</div>
				<a  title="Delete this image" onclick="delete_ele(this)" class="ui-icon ui-icon-trash">Delete image</a>
				<textarea></textarea>
				<input type="hidden" name="temp_picture" />
			</li>
			</ul>
		</div>
	</div>
	<input type="hidden" id='site_id' value="<%= @site.id%>" />
	<div id="imgstream_change_page" style="float:left;width:49%;height:450px;overflow: auto;">
		<%= render 'shared/all_image',:objects=>@imgs_path%>
          
	</div>
	<div style="width:1250px;height:10px;">
		
	</div>
	<div style="width:100%;text-align:center;">
		<div style="padding: 20px;">
			
		<input type="button" value="提交" onclick="submit_btn()" class="blue_btn"/>

		<input type="button" value="取消" onclick="cancle_dialog()" class="blue_btn"/>
		</div>
	</div>

</div>

app/views/image_streams/_edit_imgstream.html.erb
<div style="height:100%;padding:10px;margin:auto;background:white;">

	<div style="width:100%;margin-bottom: 5px ;text-align: center;">
		<input type="hidden" id="page_type" value="edit">
		<h1  > 编辑图片流页
		<br/>
		标题：<span class="check">*</span>
		<input type="text" id="title" value="<%= @page.title%>" />
		文件名：<span class="check">*</span>
		<input type="hidden"  id="name" value="<%= @page.file_name.split('.')[0...-1].join('.')%>"/>
		<input type="text" disabled  value="<%= @page.file_name.split('.')[0...-1].join('.')%>"/>.html
		</h1>
		访问权限：是
		<input type="radio" value=1 name="w" <%= (@page.authenticate ? 'checked':'')%>/>
		否
		<input type="radio" value=0 name="w" <%= (!@page.authenticate ? 'checked':'')%>/>
	</div>
	<div id="trashdiv" style="float:left;width:51%;height:450px;padding:0%;overflow: auto;">
		<div id="trash" class="ui-widget-content ui-state-default"style="margin:0px 35px;width:420px;background:white;float:right;">
			<h4 class="ui-widget-header"><span class="ui-icon ui-icon-folder-collapsed">Document</span> 您的图片区 <img src="/assets/add.png" alt="添加空白区域"  onclick="add()" style="position: relative;left:322px;cursor:pointer;"/></h4>
			<ul class='gallery ui-helper-reset' id="trashh" >
			<% (0..@image_text.img_path.length-1).each do |i|%>
			<li  class="ui-widget-content ui-corner-tr" style='width: 186px;' >
				<!--截小的图片-->
				<div style="height:144px;" >
					<%img_path=Rails.root.to_s + '/public'+@image_text.img_path[i]%>
                    <%image = MiniMagick::Image.open(img_path) if File.exists?(img_path)%>
                    <% if image %>
				   <img  src="<%= @image_text.img_path[i]%>" <%= image&&image["height"]*186/image["width"]>144 ? "height='144' width=#{ image['width']*144/image['height']}" : "width='186' height = #{image['height']*186/image['width']}" %>/>
				   <% end %>
				</div>
				<input  type="hidden" value="<%= @image_text.img_path[i]%>">
				<a  title="Delete this image" onclick="delete_ele(this)"  class="ui-icon ui-icon-trash">Delete image</a>
				<textarea><%= @image_text.content[i]%></textarea>
			</li>
			<%end%>
			</ul>
		</div>
	</div>
	<input type="hidden" id='site_id' value="<%= @site.id%>" />
	<input type="hidden" id='page_id' value="<%= @page.id%>" />
	<div id="imgstream_change_page" style="float:left;width:49%;height:450px;overflow: auto;">
		<%= render 'shared/all_image',:objects=>@imgs_path%>
	</div>
	<div style="width:100%;text-align:center; margin-top: 5px;">
		<input type="button" value="提交" onclick="submit_btn()" class="blue_btn"/>

		<input type="button" value="取消"   onclick="cancle_dialog()" class="blue_btn"/>
	</div>

</div>

app/views/image_streams/_image_pages.html.erb
<div class="page_content ">
  <div class="page_tit">
    <%=link_to '新建图片流页' ,new_site_image_stream_path(@site),  class:"blue_btn scd_btn" %>
    </div>
    <div class="page_txt">
      <table class="table1" >
        <tr>
          <th width="100">标题</th>
          <th width="300">路径</th>
          <th width="50">访问控制</th>
          <th width="300">操作</th>
        </tr>

        
        
        <% @image_stream_pages.each do |page| %>
          <tr id="<%= page.id %>">
            <td class="title"><%= page.title %></td>
            <td class="path"><%= "/sites/static" + "?path_name=" + page.path_name %></td>
            <td class="authenticate"><%= if_authenticate(page) %></td>
            <td>
              <%= link_to "访问权限" , if_authenticate_site_page_path(@site,page),:remote => true, :class => "blue_btn"%>
              <%= link_to "编辑" , edit_site_image_stream_path(@site,page), :class => "blue_btn"%>
              <%= link_to "删除" , site_image_stream_path(@site, page),:method => :delete, :confirm => "确定删除吗？", :class => "blue_btn"%>
              <%= link_to "预览" , "/sites/static" + "?path_name=" + page.path_name, :target =>"_blank" , :class => "blue_btn page_preview"%>
            </td>
          </tr>
        <% end %>
      </table>
    </div>

  
    <div class="clear"></div>
    <div class="digg_pagination" style="margin:0 auto;text-align: center;">
      <%= will_paginate  @image_stream_pages,:previous_label=>'上一页',:next_label=>'下一页'%>
    </div>
    <div class="page_act"></div>
</div>

app/views/image_streams/change.js.erb
$("#tupian").html('<%=j (render 'shared/form_images')%>');
$(function() {
     var editor = KindEditor.create('textarea[class="it_content"]', {
                          resizeMode : 1,
                          width : "400px",
                          items : ['source',
                                  'fontname', 'fontsize', '|', 'forecolor', 'hilitecolor', 'bold', 'italic', 'underline',
                                  'removeformat', '|', 'justifyleft', 'justifycenter', 'justifyright', 'insertorderedlist',
                                  'insertunorderedlist']
                  });

    // 定义图片库, drop area
   // var $gallery = $( ".picRes" ),
   // $input = $( ".image_area img" );

    // 使图片库里面的元素可托拽
   // it_drag($( "li", $gallery ));

    // drop 元素
   // it_drop($input);
 var $gallery = $( ".picRes" ),
  $input = $( ".homeMenu li" );

  // 使图片库里面的元素可托拽
  it_drag($( ".picBox", $gallery ));

  // drop 元素
  it_drop($input);
  $input=$( ".homeBg span" );
  it_drop($input);

});

app/views/image_streams/destroy.js.erb
$("#img_table").html('<%=render 'image_pages'%>');

app/views/image_streams/edit.html.erb
<div class="main_container ">
	<input type="hidden" id="page_type" value="edit" />
	<input type="hidden" id="site_id" value="<%= @site.id%>" />
	<input type="hidden" id="page_id" value="<%= @page.id if @page%>" />
	<%= render '/shared/left_panel' %>
	<div class="main_cont">
          
		<div class="tit">
			<span>标题：</span>
			<input id="title" type="text" value="<%= @page.title%>" />
			<span>文件名：</span>
			<input type="hidden"  id="name" value="<%= @page.file_name.split('.')[0...-1].join('.')%>"/>
			<input type="text" disabled  value="<%= @page.file_name.split('.')[0...-1].join('.')%>"/>
			<span>.html</span>
		</div>
		<div class="tempChoice tempChoice2">

		</div>
		<hr class="cf" color="#bcbcbc" />
		<div class="iphoneVirtual" style="overflow: auto;max-height: 568px;width: 337px;">
			<form class="pic_form" method="post" style="min-height: 570px;width: 320px;">
				<div class="picStream cf">

					<% (0..@image_text.img_path.length-1).each do |i|%>

					<div class="picStrBox">
						<span class="close" onclick="delete_ele(this)"></span>
						<div class="imgDiv">
							<span> <% img_path=Rails.root.to_s + '/public'+@image_text.img_path[i]%>
								<% image = MiniMagick::Image.open(img_path) if File.exists?(img_path)%>
								<% if image %> <img  src="<%= @image_text.img_path[i]%>" <%= image&&image["height"]*145/image["width"]>145 ? "height='145' width=#{ image['width']*145/image['height']}" : "width='145' height = #{image['height']*145/image['width']}" %>/>
								<% end %> </span>
							<input  type="hidden"  class="temp_picture" value="<%= @image_text.img_path[i]%>" />
						</div>
						<textarea><%= @image_text.content[i]%></textarea>
						<input type="hidden" name="pic_text[]" value="<%= @image_text.content[i]%>"/>
					</div>

					<%end%>

				</div>
			</form>
			<div class="iphvAct">
				<input type="button" class="blue_btn" onclick="add_imgstream_item()" value="添加图片块">
				</input>
			</div>
		</div>
		<div id="tupian">
			<%= render 'shared/form_images',:objects => @imgs, :from => "main_page" %>
		</div>

	</div>
	<div class="pageAct" >
		<button class="blue_btn" onclick="submit_imgstream()">
			保存
		</button>
	</div>
</div>
<script type="text/javascript">
	$input = $(".picStrBox .imgDiv span");
	// drop 元素
	can_it_drop($input); 
</script>

app/views/image_streams/img_stream.html.erb
<div class="main_container">
  <%= render '/shared/left_panel' %>
  <div class="main_cont">
    <%= render '/shared/page_title' %>

    <!--显示pages列表-->
    <div class="tabDiv" id="img_table">
      <%= render 'image_pages'%>
    </div>
  </div>
</div>
<!--添加图片的主体-->
<div class="second_box newPage">
  <div class="second_content second_content2" style="width: 1000px; margin: 20px auto; background: #ffffff; padding: 20px; min-height: 680px">
    <span class="close" >关闭</span>
    <div id="image_text_container">

    </div>
  </div>
</div>
<div id="viewLarge"></div>

<script>
  $(function() {
    //add按钮

    $("#add_text_img").click(function() {
      show_tag($("#image_text_container"));

    });
  });
</script>