config/routes.rb
MicroWebsite::Application.routes.draw do

  devise_for :users, :controllers => { :passwords => "passwords" , :registrations => "registrations",:sessions=>'sessions'} do
    get "change", :to => "devise/registrations#edit"
    get "change_password", :to => "devise/passwords#change"
    get "signin", :to => "devise/sessions#new"
    get "signup", :to => "devise/registrations#new"
    get "signout", :to => "devise/sessions#destroy"
  end

  get "user/manage/:type", :to=>"users#index"
  post "user/disable/:uid", :to=>"users#disable"
  post "user/enable/:uid", :to=>"users#enable"
  get "user/delete/:uid", :to=>"users#delete"
  match 'obtain_award', :to=>'awards#obtain_award' ,via: 'get'
  match 'obtain_qr_code_award', :to=>'qr_code_awards#obtain_award' ,via: 'get'
  post "site/verify/:sid",:to=>"sites#verify"
  post "site/change_status/:sid/:status",:to=>"sites#change_status"
  match "/sites/static", :to => "pages#static"
  match '/destroy_site' ,:to=>'sites#destroy_site' ,via: 'get'
  match "/sites/:site_id/pages/preview", :to => "pages#preview", :as => "preview"
  match "/sites/:site_id/pages/form_preview", :to => "pages#form_preview", :as => "form_preview"
  match "/get_token", :to => "pages#get_token", :as => "get_token", via: 'get'
  match "/get_award_url", :to => "awards#get_award_url", :as => "get_award_url", via: 'get'
  match "/record_award", :to => "awards#record_award", :as => "record_award", via: 'post'
  match "/check_if_watch", :to => "awards#check_if_watch", :as => "check_if_watch", via: 'get'
  match '/check_zip' ,to: 'resources#is_not_repeat' ,via: 'get'
  match '/change_status' ,to: 'sites#change_each_status' ,via: 'get'
  match '/allimg' ,to: 'resources#allimage' ,via: 'get'
  match 'image_text_page' ,to: 'image_streams#create_imgtxt' , via: 'post'
  match 'imgtxt_edit_update' ,to: 'image_streams#edit_update' ,via: 'post'
  match '/delete_post' ,to: 'posts#delete_post' ,via: 'get'
  match '/top' ,to: 'posts#top' ,via: 'get'
  match '/untop' ,to: 'posts#untop' ,via: 'get'
  match '/search_sites' ,to: 'sites#search',via: 'get'
  match '/model_page' ,to: 'pages#model_page',via: 'post'
  match '/sites/:site_id/app_managements/get_form_date' => 'app_managements#get_form_date', :as => :preview_visits, :via => :post
  match '/submit_redirect' => 'app_managements#submit_redirect', :as => :submit_redirect, :via => :get
  match '/get_form_date' => 'client_forms#get_form_date', :as => :preview_visits, :via => :post
  match '/get_qr_image' ,to:"weixins#get_qr_image"
  match '/get_qr_img_by_url' ,to:"weixins#get_qr_img_by_url"
  match '/dispose_award' ,to:"weixins#dispose_award"
  # Sample resource route with options:
  namespace :api do
    resources :clients do
      collection do
        post :login, :message_detail, :refresh, :del_recent_client, :get_token
        post :edit_client, :set_receive, :set_undisturbed
      end
    end
    resources :messages do
      collection do
        post :make_record, :edit_record, :send_message_to_user
      end
    end
  end
  resources  :weixins do
    member do
      get :get_qr_image
    end
  end
  resources :sites do
    member do
      post :verify_site
    end
    resources :micro_messages 
    resources :micro_imgtexts
    resources :weixin_replies
    resources :app_managements do
      collection do        
        post :create_client_info_model

      end
    end
    resources :qr_codes do
      collection do
        get :after_scan
      end
    end

    resources :qr_code_awards  do
      get :win_award_info
    end

    resources :awards do
      get :win_award_info
      collection do
        get :template
        post :save_template
      end
      member do
        get :change
      end
    end
    resources :posts do
      collection do
        get :bbs, :see_more

      end
      member do
        get :bbs_detail,:star
      end
      resources :replies do
        collection do
          get :see_more
        end
        member do
          get :verifyt,:verifyf,:verify
        end
      end
    end
    
    resources :resources
    resources :pages do
      resources :form_datas
      collection do
        get :sub, :form, :style, :sub_new,  :form_new ,:tmlt_sub_new,:change
        post :preview, :save_template3,:tmlt_sub_create,:zdy_sub_create
      end
      member do
        get :sub_edit,:form_edit, :if_authenticate, :sub_preview ,:tmlt_sub_edit
        post :submit_queries,:tmlt_sub_update
      end
    end
    
    resources :forms do
      member do
        get :submit_redirect
      end
    end

    resources :image_streams do
      #对集合进行操作
      collection do
        get :img_stream
      end
      #对单个进行操作
      member do
        get :edit_itpage,:change
      end
    end
    resources :image_texts do
      collection do
        post :preview
      end
      member do
        put :it_preview
        get :change
      end
    end
    resources :reminds do
      collection do
        post :create_records,:message_record
      end
      member do
      end
    end
  end
  match "/weixins/accept_token" => "weixins#accept_token"

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  devise_scope :user do
    root to: "devise/sessions#new"
  end

  # See how all your routes lay out with "rake routes"


  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
  # match '/:path_name',:to => "pages#static", :path_name => /\w+\/.+\.html/
end

app/views/shared/_form_images.html.erb
<% from ||= "" %>
<div class="picChoice picRes" style="display: <%= from == "main_page"&&@site.template.present? && @site.template == Constant::Template[:temp4] ? "none" : "block" %>">
  <% @imgs_path.each do |img|%>
    <% img_path=Rails.root.to_s + '/public/allsites/'+(img.path_name) %>
    <% image = MiniMagick::Image.open(img_path) if File.exists?(img_path) %>
    <% if image %>
      <div class="picBox">
        <img src="/allsites/<%= img.path_name %>" alt="<%= File.basename(img.path_name) %>" onclick="viewLargerImage(this)"
             <%= image&&image["height"]/image["width"]>=1 ? "height='140' width=#{ image['width']*140/image['height']}" : "width='140' height=#{image['height']*140/image['width']}" %> />
        <span><%= img.path_name.split("/")[-1].length>6 ? "#{img.path_name.split('/')[-1][0..5]}..." :img.path_name.split("/")[-1]%></span>
      </div>
    <% end %>
  <%end%>
  <div style="clear: both"></div>
  <%if @imgs_path.present?%>
    <div class="digg_pagination" style="margin-left:5px;text-align: center; width:590px">
      <%= will_paginate @imgs_path,:previous_label=>'上一页',:next_label=>'下一页'  %>
    </div>
  <%end%>
</div>

<div id="viewLarge"></div>
<script>
  var aarr = $(".pagination").find("a");
  aarr.each(function(){
    $(this).attr("data-remote",true);
    $(this).attr("data-type",'script');
    //alert($(this).attr("href"))
    var page_param = $(this).attr("href").split("?")[1]
    $(this).attr("href","<%= change_site_pages_path(@site) %>?" + page_param);
  });
 
</script>

app/views/shared/_head_nav.html.erb
<div class="header">
		<div class="logo"></div>
		<div class="menu">
			<ul>

				<li class="item1"><a href="/sites" style="color:white;">站点首页</a></li>
				<%if controller.controller_name=='sites'%>
                                <li class="item2">新建站点
					<ul class="tempBox">
                                          <div class="ul_cor_div"><span class="ul_cor"></span></div>
						<li class="temp1" onclick="create_site(1)"></li>
						<li class="temp2" onclick="create_site(2)"></li>
						<li class="temp3" onclick="create_site(3)"></li>
						<li class="temp4" onclick="create_site(4)" title="自定义"></li>
					</ul>
				</li>
                                <%end%>
			</ul>
		</div>
		<div class="userInfo">
			<span><%=current_user.name%></span>|
			<a href="/signout">退出</a>
		</div>
                <%if controller.controller_name=='sites'%>
		<div class="searchBox">
			<input type="text" id="site_key" name="key"/>
			<button class="search_btn" onclick="search_site()">搜索</button>
		</div>
                <%end%>
	</div>

app/views/shared/_left_panel.html.erb
<div class="leftSide">
  <div class="resDiv">
    <%= link_to(site_resources_path(@site)) do %>
      <button class="resBtn">资源包</button>
    <% end %>
  </div>
  <ul class="leftMenu">
    <%= link_to(site_pages_path(@site)) do%>
      <li class="leftItem1 <%= controller_name == "pages" && controller.action_name == "index" ? 'leftItem_selected' : '' %>">
        首页
      </li>
    <% end %>
    <%= link_to(sub_site_pages_path(@site)) do %>
      <li class="leftItem2 <%= controller.action_name == "sub" ||
                               controller.action_name == "tmlt_sub_new" ||
                               controller.action_name == "tmlt_sub_edit" ? 'leftItem_selected' : '' %>">
        其他页
      </li>
    <% end %>
    <%= link_to(site_forms_path(@site)) do%>
      <li class="leftItem3 <%= controller_name == "forms" ? 'leftItem_selected' : '' %>">
        表单
      </li>
    <% end %>
    <%= link_to(img_stream_site_image_streams_path(@site)) do %>
      <li class="leftItem4 <%= controller_name=="image_streams" ? 'leftItem_selected' : '' %>">
        图片流
      </li>
    <% end %>
    <%= link_to(site_image_texts_path(@site)) do %>
      <li class="leftItem5 <%= controller_name == "image_texts" ? 'leftItem_selected' : '' %>">
        图文
      </li>
    <% end %>
    <%=link_to( template_site_awards_path(@site)) do%>
      <li class="leftItem6 <%= controller.controller_name == "awards"&&controller.action_name=="template" ? "leftItem_selected":"" %>">
        刮刮乐
      </li>
    <%end%>
    <%=link_to(site_awards_path(@site)) do%>
      <li class="leftItem7 <%= controller.controller_name == "awards"&&controller.action_name!="template" ? "leftItem_selected":"" %>">
        奖品
      </li>
    <% end %>

    <%=link_to site_app_managements_path(@site) do%>
      <li class="leftItem8 <%= controller.controller_name == "app_managements" ? "leftItem_selected":"" %>">
        APP
      </li>
    <% end %>
    <%=link_to site_micro_messages_path(@site) do%>
      <li class="leftItem9 <%= controller.controller_name == "micro_messages" ? "leftItem_selected":"" %>">
        图文消息
      </li>
    <% end %>
    <%=link_to site_weixin_replies_path(@site) do%>
      <li class="leftItem10 <%= controller.controller_name == "weixin_replies" ? "leftItem_selected":"" %>">
        自动回复
      </li>
    <%=link_to site_qr_codes_path(@site) do%>
      <li class="leftItem11 <%= controller.controller_name == "qr_codes" ? "leftItem_selected":"" %>">
        二维码
      </li>
    <% end %>
    <% end %>
      <%=link_to site_qr_code_awards_path(@site) do%>
      <li class="leftItem12 <%= controller.controller_name == "qr_code_awards" ? "leftItem_selected":"" %>">
        二维码奖品
      </li>
    <% end %>
  </ul>
</div>

app/views/shared/_links.html.erb
<div class="second_box addLink">
  <div class="second_content">
    <span class="close" >关闭</span>
    <h1>菜单一链接</h1>
    <div id="linkPage">
      <div class="tabs">
        <span class="tab curr">站内链接</span>
        <span class="tab">站外链接</span>
        <div class="tabsLine"></div>
      </div>
      <input type="hidden" class="hiddenIndex" />
      <input type="hidden" class="hiddenBlock" />
      <div class="tabDiv curr inside">
        <% @sub_pages.each do |page| %>
          <input type="radio" name="insite_link" value="<%= "/sites/static?path_name=" + page.path_name %>"/>
          <span class="radioVal" style="text-align:left; padding: 0"><%= page.title %></span>
        <% end %>
      </div>
      <div class="tabDiv outside">
        <label>站外链接输入：</label><input type="text" name="outside_link" />
      </div>
      <div class="scdBox_act">
        <button class="blue_btn" onclick="setLink('<%= from %>')">确认</button>
        <button class="blue_btn cancel">取消</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_page_title.html.erb
<h1><%= @site.name %>(<%= status_desc @site.status %>)</h1>
<div class="tempChoice">
  <% if @page && @page.main? %>
    <span>模板：</span>
    <ul class="tmp_list">
      <li class="temp1 <%= !@site.template.present? || @site.template == Constant::Template[:temp1] ? "hover" : "" %>"></li>
      <li class="temp2 <%= @site.template.present? && @site.template == Constant::Template[:temp2] ? "hover" : "" %>"></li>
      <li class="temp3 <%= @site.template.present? && @site.template == Constant::Template[:temp3] ? "hover" : "" %>"></li>
      <li class="temp4 <%= @site.template.present? && @site.template == Constant::Template[:temp4] ? "hover" : "" %>"></li>
    </ul>
  <% elsif @page && @page.sub? %>
  <% end %>
</div>
<button class="blue_btn setBtn" onclick="change_status('<%=@site.id%>',2,'提交审核')">提交审核</button>
<hr class="cf" color="#bcbcbc" />

app/views/shared/_pop_container.html.erb
<!-- 子页，表单访问控制 -->
<div class="second_box newPage">
  <div class="second_content">
    <span class="close" >关闭</span>
    <div id="sub_form_authenticate">

    </div>
  </div>
</div>

<!-- 编辑用户 -->
<div class="second_box uinfo_chg">
  <div class="second_content">
    <span class="close" >关闭</span>
    <div id="edit_user">

    </div>
  </div>
</div>

<!-- 修改密码 -->
<div class="second_box newPage">
  <div class="second_content">
    <span class="close" >关闭</span>
    <div id="edit_password">

    </div>
  </div>
</div>


<!-- 审核站点 -->
<div class="second_box newPage">
  <div class="second_content">
    <span class="close" >关闭</span>
    <div id="verify_site">

    </div>
  </div>
</div>

app/views/shared/_tishi_alert.html.erb
<div class="tab_alert second_box" style="z-index: 100">
  <div class="second_content" style="font-size:20px;margin: 200px auto;width: 300px;background: #3696E0;padding: 20px;">
    <span class="close" id="close_flash" style="float:right;" ></span>
    <div class="alert_h">
    </div>
  </div>
</div>

app/views/shared/temp.html.erb
<%=@temp%>