config/routes.rb
MicroWebsite::Application.routes.draw do

  devise_for :users, :controllers => { :passwords => "passwords" , :registrations => "registrations",:sessions=>'sessions'} do
    get "change", :to => "devise/registrations#edit"
    get "change_password", :to => "devise/passwords#change"
    get "signin", :to => "devise/sessions#new"
    get "signup", :to => "devise/registrations#new"
    get "signout", :to => "devise/sessions#destroy"
  end

  get "user/manage/:type", :to=>"users#index"
  post "user/disable/:uid", :to=>"users#disable"
  post "user/enable/:uid", :to=>"users#enable"
  get "user/delete/:uid", :to=>"users#delete"
  match 'obtain_award', :to=>'awards#obtain_award' ,via: 'get'
  match 'obtain_qr_code_award', :to=>'qr_code_awards#obtain_award' ,via: 'get'
  post "site/verify/:sid",:to=>"sites#verify"
  post "site/change_status/:sid/:status",:to=>"sites#change_status"
  match "/sites/static", :to => "pages#static"
  match '/destroy_site' ,:to=>'sites#destroy_site' ,via: 'get'
  match "/sites/:site_id/pages/preview", :to => "pages#preview", :as => "preview"
  match "/sites/:site_id/pages/form_preview", :to => "pages#form_preview", :as => "form_preview"
  match "/get_token", :to => "pages#get_token", :as => "get_token", via: 'get'
  match "/get_award_url", :to => "awards#get_award_url", :as => "get_award_url", via: 'get'
  match "/record_award", :to => "awards#record_award", :as => "record_award", via: 'post'
  match "/check_if_watch", :to => "awards#check_if_watch", :as => "check_if_watch", via: 'get'
  match '/check_zip' ,to: 'resources#is_not_repeat' ,via: 'get'
  match '/change_status' ,to: 'sites#change_each_status' ,via: 'get'
  match '/allimg' ,to: 'resources#allimage' ,via: 'get'
  match 'image_text_page' ,to: 'image_streams#create_imgtxt' , via: 'post'
  match 'imgtxt_edit_update' ,to: 'image_streams#edit_update' ,via: 'post'
  match '/delete_post' ,to: 'posts#delete_post' ,via: 'get'
  match '/top' ,to: 'posts#top' ,via: 'get'
  match '/untop' ,to: 'posts#untop' ,via: 'get'
  match '/search_sites' ,to: 'sites#search',via: 'get'
  match '/model_page' ,to: 'pages#model_page',via: 'post'
  match '/sites/:site_id/app_managements/get_form_date' => 'app_managements#get_form_date', :as => :preview_visits, :via => :post
  match '/submit_redirect' => 'app_managements#submit_redirect', :as => :submit_redirect, :via => :get
  match '/get_form_date' => 'client_forms#get_form_date', :as => :preview_visits, :via => :post
  match '/get_qr_image' ,to:"weixins#get_qr_image"
  match '/get_qr_img_by_url' ,to:"weixins#get_qr_img_by_url"
  match '/dispose_award' ,to:"weixins#dispose_award"
  # Sample resource route with options:
  namespace :api do
    resources :clients do
      collection do
        post :login, :message_detail, :refresh, :del_recent_client, :get_token
        post :edit_client, :set_receive, :set_undisturbed
      end
    end
    resources :messages do
      collection do
        post :make_record, :edit_record, :send_message_to_user
      end
    end
  end
  resources  :weixins do
    member do
      get :get_qr_image
    end
  end
  resources :sites do
    member do
      post :verify_site
    end
    resources :micro_messages 
    resources :micro_imgtexts
    resources :weixin_replies
    resources :app_managements do
      collection do        
        post :create_client_info_model

      end
    end
    resources :qr_codes do
      collection do
        get :after_scan
      end
    end

    resources :qr_code_awards  do
      get :win_award_info
    end

    resources :awards do
      get :win_award_info
      collection do
        get :template
        post :save_template
      end
      member do
        get :change
      end
    end
    resources :posts do
      collection do
        get :bbs, :see_more

      end
      member do
        get :bbs_detail,:star
      end
      resources :replies do
        collection do
          get :see_more
        end
        member do
          get :verifyt,:verifyf,:verify
        end
      end
    end
    
    resources :resources
    resources :pages do
      resources :form_datas
      collection do
        get :sub, :form, :style, :sub_new,  :form_new ,:tmlt_sub_new,:change
        post :preview, :save_template3,:tmlt_sub_create,:zdy_sub_create
      end
      member do
        get :sub_edit,:form_edit, :if_authenticate, :sub_preview ,:tmlt_sub_edit
        post :submit_queries,:tmlt_sub_update
      end
    end
    
    resources :forms do
      member do
        get :submit_redirect
      end
    end

    resources :image_streams do
      #对集合进行操作
      collection do
        get :img_stream
      end
      #对单个进行操作
      member do
        get :edit_itpage,:change
      end
    end
    resources :image_texts do
      collection do
        post :preview
      end
      member do
        put :it_preview
        get :change
      end
    end
    resources :reminds do
      collection do
        post :create_records,:message_record
      end
      member do
      end
    end
  end
  match "/weixins/accept_token" => "weixins#accept_token"

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  devise_scope :user do
    root to: "devise/sessions#new"
  end

  # See how all your routes lay out with "rake routes"


  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
  # match '/:path_name',:to => "pages#static", :path_name => /\w+\/.+\.html/
end

app/models/award.rb
class Award < ActiveRecord::Base
  attr_accessible :begin_date, :end_date, :name, :no_operation_number, :total_number
  belongs_to :site
  has_many :award_infos, dependent: :destroy
  TYPES={ggl:0,qr_code:1}
 # scope :qr_code_awards,{ condition:"types = 1" }
  #scope :weixin_awards,{ condition:"types = 1" }
  
  scope :ggl,{ conditions:"types = 0" } #刮刮乐
  scope :qr_code,{ conditions:"types = 1" } #二维码

end

app/controllers/awards_controller.rb
#encoding:utf-8
class AwardsController < ApplicationController
  skip_before_filter :authenticate_user!, :only => [:show, :record_award, :get_award_url, :check_if_watch]
  before_filter :get_site, :except => [:show, :record_award, :get_award_url, :check_if_watch]
  layout 'sites'
  SITE_PATH = "/public/allsites/%s/"
  def index
    @awards=Award.where(["site_id= ? and types = 0 ",@site.id] )
  end

  def new
    @award = @site.awards.build

  end

  def create
    @award=@site.awards.build
    @award.name=params[:award][:name]
    @award.total_number=params[:award][:total_number]
    @award.no_operation_number=params[:award][:total_number]
    @award.begin_date=params[:award][:begin_date]
    @award.end_date=params[:award][:end_date]

    if @award.save
      save_award_item
      flash[:success]='新建成功'
      redirect_to site_awards_path
    else
      flash[:error]='新建失败'
      render 'new'
    end
  end

  def destroy
    @award=Award.find_by_id(params[:id])
    if @award.destroy
      flash[:success]='删除成功'
      redirect_to site_awards_path
    else
      flash[:success]='删除失败'
      render 'index'
    end
  end

  def edit
    @award=Award.find_by_id(params[:id])
  end

  def update
    @award=Award.find_by_id(params[:id])
    name=params[:award][:name]
    total_number=params[:award][:total_number]
    begin_date=params[:award][:begin_date]
    end_date=params[:award][:end_date]
    if @award.update_attributes(name:name,total_number:total_number,begin_date:begin_date,end_date:end_date )
      update_award_item
      flash[:success]='更新成功'
      redirect_to site_awards_path
    else
      flash[:success]='更新失败'
      render 'edit'
    end
  end

  def show
    @award = Award.find_by_id(params[:id])
    @open_id = params[:secret_key]
    current_time = Time.now.strftime("%Y-%m-%d")
    if @award
      if current_time >= @award.begin_date.to_s && current_time <= @award.end_date.to_s
        award_infos = @award.award_infos
        user_award = UserAward.where(:open_id => @open_id, :award_id => @award.id)[0] #当前open_id是否刮过
        if !user_award
          total_num = @award.total_number #总的奖券数
          has_award_num = award_infos.sum(:number) #有奖的奖券总数
          no_award_num = total_num - has_award_num  #无奖的奖券总数
          
          no_operation_number = @award.no_operation_number  #剩余的奖券
          scratched_award_infos, scratched_has_award_infos,scratched_no_award_infos = get_scratched_award(@award)
          
          scratched_has_award_infos_hash = scratched_has_award_infos.group_by{|ua| ua.award_info_id} #刮过的，有奖的奖券,奖券id分类
          
          #所有索引放进一个string
          award_str = ""
          award_infos.each do |ai|
            award_info_id = ai.id
            if scratched_has_award_infos_hash[award_info_id].present?
              left_number = ai.number - scratched_has_award_infos_hash[award_info_id].length #剩余的未刮过的有奖奖券
            else
              left_number = ai.number
            end

            award_str << (ai.award_index.to_s) * left_number if left_number > 0
          end
          left_no_scratched_no_award_num = no_award_num - scratched_no_award_infos.length  #剩余的未刮过的无奖奖券
          award_str << "0" * left_no_scratched_no_award_num  if left_no_scratched_no_award_num> 0 #无奖项默认0
          award_arr = award_str.split("")  #string 转换成数组
          if award_arr.present?
            #乱序数组两次，随机索引数
            award_index = award_arr.shuffle.shuffle[rand(no_operation_number)]  #抽取出来的奖项索引
            # award_index = 1
            if award_index == "0"
              @status = 0  #未中奖
              @img = "/assets/thanks.png"  #谢谢参与
            else
              @status = 1  #中奖
              @award_info = @award.award_infos.where("award_index = ?", award_index.to_i)[0]
              @img = @award_info.img if @award_info
            end
          else
            @status = 4  #奖券已抽完
          end
        else
          award_info = user_award.award_info
          @status = 2  #已经抽过奖
        end
      else
        @status = 3  #奖券未开始或者已经过期
        @img = false 
      end
      render :layout => false
    else
      render(:file  => "#{Rails.root}/public/404.html",
        :layout => nil,
        :status   => "404 Not Found")
    end
    
  end
  
  def win_award_info
    @award=Award.find_by_id(params[:award_id])
    @award_infos =AwardInfo.where("award_id = #{params[:award_id]}")
    award_info_id=[]
    @award_infos.each do |f|
      award_info_id<<f.id
    end
    @userinfos =UserAward.where( "award_info_id in ( #{award_info_id.join(',')} )")
    @awards_is = @userinfos.group_by{|a| a[:award_info_id]} unless @award_infos.nil?
  end
  
  #领奖
  def obtain_award
    @user_award=UserAward.find_by_id(params[:id])
    if @user_award && @user_award.update_attribute(:if_checked,true)
      flash[:success]='领取成功'
      
      redirect_to site_awards_path(@site)
    else
      flash[:success]='领取失败'
      render 'index'
    end
  end
  
  def record_award
    
    begin
      open_id, award_id, award_info_id, phone = params[:open_id], params[:award_id], params[:award_info_id], params[:phone]
      award = Award.find_by_id(award_id)
      user_award = UserAward.where(:open_id => open_id, :award_id => award_id)[0] #当前open_id是否刮过
      
      unless user_award.present?
        UserAward.transaction do
          if open_id.present? && open_id != "null"
            if award_info_id.present? #抽到奖
              
              # 接收手机号码作为secret_code存入数据库
              # 记录 刮刮记录
              user_award = UserAward.create(:open_id => open_id, :award_info_id => award_info_id, :award_id => award_id,
                :secret_code => phone, :if_checked => false)
              
              #减少奖券数量
              award.update_attribute(:no_operation_number, award.no_operation_number - 1) if award
            else #没抽到奖
            
              #记录 刮刮记录
              user_award = UserAward.create(:open_id => open_id, :award_info_id => award_info_id, :award_id => award_id,
                :secret_code => nil, :if_checked => false)
              #减少奖券数量
              award.update_attribute(:no_operation_number, award.no_operation_number - 1) if award
            end
          end
        end
      else
        user_award.update_attribute(:secret_code, phone) if phone
      end
      msg = "success"
    rescue
      msg = "error"
    end
    respond_to do |f|
      f.json{
        render :json => {:msg => msg, :saved_phone => user_award.secret_code.present? ? true : false}
      }
      f.js{}
    end
  end

  def get_award_url
    site_root_path = params[:site_root_path]
    site = Site.find_by_root_path(site_root_path)
    current_time = Time.now.strftime("%Y-%m-%d")
    award = site.awards.where("begin_date <= ? and end_date >= ?", current_time, current_time).first if site
    render :text => award ? site_award_url(site, award) : "none"
  end

  def check_if_watch
    open_id = params[:secret_token]
    ua = UserAward.find_by_open_id(open_id)
    render :text => ua ? "1" : "0"
  end
  def template
    resources_for_select
    @awards = @site.awards.ggl
    @template = Page.where("site_id = #{@site.id} and types=1 and template = 2")[0]
  end

  def save_template
    resources_for_select
    html_content = params[:html_content]
    @award_id = params[:award_id]
    title = params[:name]
    name = params[:title]+".html"
    vcitem = params[:vcitem]
    top_img = params[:top]
    bot_img = params[:bot]
    template = Page.where("site_id = #{@site.id} and types=1 and template = 2")[0]
    if template
      if template.update_attributes(title:title,file_name:name,authenticate:vcitem,page_html:html_content)
        save_as_award top_img,bot_img,name,@award_id
        flash[:success] = '更新成功'
        redirect_to template_site_awards_path(@site)
      else
        flash[:error] = '更新失败'
        render 'template'
      end
    else
      path = "/#{@site.root_path}/#{name}"
      if Page.create(title:title,file_name:name,authenticate:vcitem,types:1,template:2,site_id:@site.id,path_name:path,page_html:html_content)
        save_as_award top_img,bot_img,name,@award_id
        flash[:success] = '创建成功'
        redirect_to template_site_awards_path(@site)
      else
        flash[:error] = '创建失败'
        render 'template'
      end
    end
    
  end
  #给图片流进行分页（shared/all_img）
  def change
    @site=Site.find(params[:site_id])
    @imgs_pathes = @site.resources.where("path_name like '%.jpg' or path_name like '%.gif' or path_name like '%.png' or path_name like '%.jpeg' ")
    @imgs_path = @imgs_pathes.paginate(:page =>params[:id],:per_page=>12)
  end

  private
  #保存为模版页
  def save_as_award top_img,bot_img,name,award
    ifream = "
     
"
    
    if award!=""
      ifream = "<input type='hidden' id='secret_key' value='/sites/#{@site.id}/awards/#{@award_id}' /><iframe id='guaguale' src='' width='190' height='41' frameborder='0' scrolling='no'></iframe>
      "
    end
    html="
      <!doctype html>
<html>
<head>
<meta charset='utf-8'>
<meta name='viewport' content='width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no'>
<title>刮刮乐</title>
<script type='text/javascript' src='/allsites/js/jQuery-v1.9.0.js'></script>
<script type='text/javascript' src='/allsites/js/award_main.js'></script>
<script src='/assets/jquery_ujs.js' type='text/javascript'></script>
<script src='/allsites/js/award.js' type='text/javascript'></script>
<link href='/allsites/style/award_style.css' rel='stylesheet' type='text/css'>
</head>

<body class='gua_bg' style='background-image: url(\"#{top_img}\");'>
	<article>
         <section class='guaArea'>
         	<div class='guaArea_iframe'>
              #{ifream}
         </div>
         </section>
         <section class='textBox' style='background-image:url(\"#{bot_img[0]}\");'></section>
         <section class='textBox' style='background-image:url(\"#{bot_img[1]}\");'></section>
    </article>
    " + page_footer(@site)+"

app/helpers/award_helper.rb
#encoding: utf-8
module AwardHelper
  def get_award_info(award_infos,id)
    award_infos.each do|award_info|
      if award_info.id==id
        return "#{award_info.name}(#{award_info.content})"
      end
    end
    nil
  end
  def get_qr_award_info(award_infos,id)
    award_infos.each do|award_info|
      if award_info.id==id
        return (get_min_by_imgpath "#{award_info.content}")
      end
    end
    nil
  end

  def reply_content(micro_message)
    if micro_message
      if micro_message.text?
        if micro_message.solid_link_flag == MicroMessage::SOLID_LINK[:ggl]
          "刮刮乐"
        elsif micro_message.solid_link_flag == MicroMessage::SOLID_LINK[:app]
          "app登记"
        else
          "一条文字"
        end
      elsif micro_message.image_text?
        "一条图文"
      end
    end
  end
end

app/views/awards/_form.html.erb
<div class="second_content second_content2"> 
	
		<span class="close" onclick="cancle_award_page()">关闭</span>
		<%=form_for [@site,@award] do |f|%>
		<h1><%=  controller.action_name=='new' ? '添加':'编辑'%>刮刮乐</h1>
		<li>
			<label>抽奖名称：</label>
			<%=f.text_field :name%>
		</li>
		<li class="dataLi">
       		<label>有效期：</label>
            <%=f.text_field :begin_date ,id:"datepicker" ,readonly:""%><span>到</span><%=f.text_field :end_date ,id:"datepicker1",readonly:""%>
        </li>
        <li class="listLi">
           	<label>奖项设置：</label>
           		
          	<ul class="award_item">
          		<%if @award.award_infos.length==0%>
				<li>奖项名：<input type="text" name="name[]"/> 奖项内容： <input type="text" name="content[]"/>奖项数：<input type="text" name="number[]" />
                                <span class="close" title="删除该奖项" onclick="remove_award_item(this)"></span></li>
				<li>奖项名：<input type="text" name="name[]"/> 奖项内容： <input type="text" name="content[]"/>奖项数：<input type="text" name="number[]"/>
                                <span class="close" title="删除该奖项" onclick="remove_award_item(this)"></span></li>
				<li>奖项名：<input type="text" name="name[]"/> 奖项内容： <input type="text" name="content[]"/>奖项数：<input type="text" name="number[]"/>
                                <span class="close" title="删除该奖项" onclick="remove_award_item(this)"></span></li>

				<%else%>
                <%@award.award_infos.each do |a_info|%>
				<li>
					<input type="hidden" class="award_item_id" name="info_id[]" value="<%= a_info.id%>"/>奖项名：<input type="text" name="name[]" value=<%= a_info.name%> /> 奖项内容：  <input type="text" name="content[]" value=<%= a_info.content%> />奖项数：<input type="text" name="number[]" value=<%= a_info.number%> />
					<span class="close" title="删除该奖项" onclick="remove_award_item(this)"></span>
				</li>
				<%end%>
                                
				<%end%>
			</ul>
        </li>
        <div class="addjx" onclick="add_award_item()"><span title="添加奖项" >+</span></div>
		<li>
           	<label>奖券数：</label>
          	<%=f.text_field :total_number %>
        </li>
		<div class="uinfo_act">
			<input type="button" class="blue_btn" onclick="check_award_form()" value='提交'/>
		</div>
		<%end%>
</div>
<script>
    $( "#datepicker" ).datepicker();
	$( "#datepicker1" ).datepicker();
	$( "#datepicker" ).datepicker("option", "dateFormat", "yy-mm-dd" );
	$( "#datepicker1" ).datepicker("option", "dateFormat", "yy-mm-dd" );
	$( "#datepicker" ).val('<%=@award.begin_date%>');
	$( "#datepicker1" ).val('<%=@award.end_date%>');
</script>

app/views/awards/change.js.erb
$("#tupian").html('<%=j (render 'shared/form_images')%>');
$(function() {
     var editor = KindEditor.create('textarea[class="it_content"]', {
                          resizeMode : 1,
                          width : "400px",
                          items : ['source',
                                  'fontname', 'fontsize', '|', 'forecolor', 'hilitecolor', 'bold', 'italic', 'underline',
                                  'removeformat', '|', 'justifyleft', 'justifycenter', 'justifyright', 'insertorderedlist',
                                  'insertunorderedlist']
                  });

    // 定义图片库, drop area
   // var $gallery = $( ".picRes" ),
   // $input = $( ".image_area img" );

    // 使图片库里面的元素可托拽
   // it_drag($( "li", $gallery ));

    // drop 元素
   // it_drop($input);
 var $gallery = $( ".picRes" ),
  $input = $( ".homeMenu li" );

  // 使图片库里面的元素可托拽
  it_drag($( ".picBox", $gallery ));

  // drop 元素
 

});

app/views/awards/edit.html.erb
<div class="main_container">
	 
	  <%=render 'form' %>
	 
</div>

app/views/awards/index.html.erb
<div class="main_container">
  <%= render '/shared/left_panel' %>
  <div class="main_cont">
    <%= render '/shared/page_title' %>
    <div class="tabDiv used">
      <div class="page_content">
        <div class="page_tit">
          <%=link_to '添加刮刮乐',new_site_award_path,remote:true,class:'blue_btn scd_btn',name:"addGgl"%>

          </div>
          <div class="page_txt">
            <table class="table1">
              <tr>
                <th>名称</th>
                <th>有效期</th>
                <th>奖项设置</th>
                <th>奖券数</th>
                <th style="width: 200px;">操作</th>
              </tr>
              <%@awards.each do |award|%>
                <tr>
                  <td><%= link_to award.name, site_award_path(@site,award), "target" => "_blank" %>
                    <br/><%=site_award_url(@site,award)%>
                  </td>
                  <td><%=award.begin_date%>到<%=award.end_date%></td>

                  <td>
                    <%award.award_infos.each do |a_info|%>
                  <li>
                    <%="#{a_info.name} #{a_info.content} 共#{a_info.number}名"%>
                  </li>
                <%end%>
                </td>
                <td><%=award.total_number%></td>
                <td>
                  <%=link_to '编辑',edit_site_award_path(@site,award),remote:true,class:"blue_btn scd_btn", name:"addGgl"%>
                    <%=link_to '获奖信息',site_award_win_award_info_path(@site,award),remote:true,class:'blue_btn scd_btn'%>
                      <%=link_to '删除',site_award_path(@site,award),confirm:'是否删除？',method: :delete, class:"blue_btn"%>

                      </td>
                      </tr>
                    <%end%>

                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="second_box addGgl">

        </div>

        <div class="second_box resInfo">

        </div>

app/views/awards/record_award.js.erb
$(".gua_tab", window.parent.document).hide();
$(".message", window.parent.document).text("信息登记成功").parents(".tishi").show();

app/views/awards/show.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    <title><%= @award.name %></title>
    <%= javascript_include_tag "jquery", "common/wScratchPad" %>
    <style type="text/css">
      * { padding: 0; margin: 0;}
    </style>
  </head>

  <body>
    <div class="content-box">
      <div id="wScratchPad" style="display:inline-block; position:relative;"></div>
    </div>
    
  </body>
</html>
<script type="text/javascript">
      $(window.parent.document).ready(function(){

      var open_id = "<%= @open_id %>";
      if(open_id != "null"){
              <% if @status == 0 || @status == 1 %>
                  var sp = $("#wScratchPad").wScratchPad({
                    image: '<%= @img %>',
                    image2: '/assets/gua.png',
                    width: '190',
                    height: '41',

                    scratchDown: function(e, percent){},
                    scratchMove: function(e, percent){},
                    scratchUp: function(e, percent){
                      var award_info_id = "<%= @award_info.try(:id) %>";
                      var award_id = "<%= @award.id %>";
                      var percent = percent;
                      dataHash = { open_id : open_id, award_info_id : award_info_id, award_id: award_id}
                      $.ajax({
                        url: "/record_award",
                        type: "post",
                        dataType: "json",
                        data: dataHash,
                        success:function(data){
                          if(award_info_id != "null" && award_info_id !="" && percent > 30 && !data['saved_phone']){
                            //show popup enter phone number
                            var windowHeight = Math.max(window.parent.document.body.scrollHeight, $(window.parent.document).height());
                            var windowWidth = window.parent.document.documentElement.clientWidth;
                            $(".mask", window.parent.document).css("height",windowHeight);
	                    $(".mask", window.parent.document).css("width",windowWidth);

                            var tabHeight = $(".tab").height();
                            var tabWidth = $(".tab").width();
                            $(".tab").css("top",(windowHeight - tabHeight)/2);
                            $(".tab").css("left",(windowWidth - tabWidth)/2);

                            $(".mask", window.parent.document).show();
                            $(".gua_tab", window.parent.document).show();
                            $("#mphone",  window.parent.document).val("");
                            $("#open_id",  window.parent.document).val(open_id);
                            $("#award_id",  window.parent.document).val(award_id);
                            $("#award_info_id",  window.parent.document).val(award_info_id);
                          }
                        },
                        error:function(data){
                          //alert("error");
                        }
                      });


                    }

                  });

            <% elsif @status == 2 %>
                  $(".mask", window.parent.document).show();
                  $(".message", window.parent.document).text("你已经抽过奖").parents(".tishi").show();
            <% elsif @status == 3 %>
                  $(".mask", window.parent.document).show();
                  $(".message", window.parent.document).text("活动已过期或者还未开始").parents(".tishi").show();
                  // $("#wScratchPad").text("活动已过期或者还未开始")
            <% elsif @status == 4 %>
                  $(".mask", window.parent.document).show();
                  $(".message", window.parent.document).text("奖券已抽完").parents(".tishi").show();
            <% end %>
        }
      else{
        $(".mask", window.parent.document).show();
        $(".message", window.parent.document).text("对不起，你没有权限抽奖").parents(".tishi").show();
      }

                  $(".gray_btn", window.parent.document).click(function(){
                  $(".mask", window.parent.document).hide();
                  $(".tab", window.parent.document).hide();
                })

                 })
    </script>