config/routes.rb
MicroWebsite::Application.routes.draw do

  devise_for :users, :controllers => { :passwords => "passwords" , :registrations => "registrations",:sessions=>'sessions'} do
    get "change", :to => "devise/registrations#edit"
    get "change_password", :to => "devise/passwords#change"
    get "signin", :to => "devise/sessions#new"
    get "signup", :to => "devise/registrations#new"
    get "signout", :to => "devise/sessions#destroy"
  end

  get "user/manage/:type", :to=>"users#index"
  post "user/disable/:uid", :to=>"users#disable"
  post "user/enable/:uid", :to=>"users#enable"
  get "user/delete/:uid", :to=>"users#delete"
  match 'obtain_award', :to=>'awards#obtain_award' ,via: 'get'
  match 'obtain_qr_code_award', :to=>'qr_code_awards#obtain_award' ,via: 'get'
  post "site/verify/:sid",:to=>"sites#verify"
  post "site/change_status/:sid/:status",:to=>"sites#change_status"
  match "/sites/static", :to => "pages#static"
  match '/destroy_site' ,:to=>'sites#destroy_site' ,via: 'get'
  match "/sites/:site_id/pages/preview", :to => "pages#preview", :as => "preview"
  match "/sites/:site_id/pages/form_preview", :to => "pages#form_preview", :as => "form_preview"
  match "/get_token", :to => "pages#get_token", :as => "get_token", via: 'get'
  match "/get_award_url", :to => "awards#get_award_url", :as => "get_award_url", via: 'get'
  match "/record_award", :to => "awards#record_award", :as => "record_award", via: 'post'
  match "/check_if_watch", :to => "awards#check_if_watch", :as => "check_if_watch", via: 'get'
  match '/check_zip' ,to: 'resources#is_not_repeat' ,via: 'get'
  match '/change_status' ,to: 'sites#change_each_status' ,via: 'get'
  match '/allimg' ,to: 'resources#allimage' ,via: 'get'
  match 'image_text_page' ,to: 'image_streams#create_imgtxt' , via: 'post'
  match 'imgtxt_edit_update' ,to: 'image_streams#edit_update' ,via: 'post'
  match '/delete_post' ,to: 'posts#delete_post' ,via: 'get'
  match '/top' ,to: 'posts#top' ,via: 'get'
  match '/untop' ,to: 'posts#untop' ,via: 'get'
  match '/search_sites' ,to: 'sites#search',via: 'get'
  match '/model_page' ,to: 'pages#model_page',via: 'post'
  match '/sites/:site_id/app_managements/get_form_date' => 'app_managements#get_form_date', :as => :preview_visits, :via => :post
  match '/submit_redirect' => 'app_managements#submit_redirect', :as => :submit_redirect, :via => :get
  match '/get_form_date' => 'client_forms#get_form_date', :as => :preview_visits, :via => :post
  match '/get_qr_image' ,to:"weixins#get_qr_image"
  match '/get_qr_img_by_url' ,to:"weixins#get_qr_img_by_url"
  match '/dispose_award' ,to:"weixins#dispose_award"
  # Sample resource route with options:
  namespace :api do
    resources :clients do
      collection do
        post :login, :message_detail, :refresh, :del_recent_client, :get_token
        post :edit_client, :set_receive, :set_undisturbed
      end
    end
    resources :messages do
      collection do
        post :make_record, :edit_record, :send_message_to_user
      end
    end
  end
  resources  :weixins do
    member do
      get :get_qr_image
    end
  end
  resources :sites do
    member do
      post :verify_site
    end
    resources :micro_messages 
    resources :micro_imgtexts
    resources :weixin_replies
    resources :app_managements do
      collection do        
        post :create_client_info_model

      end
    end
    resources :qr_codes do
      collection do
        get :after_scan
      end
    end

    resources :qr_code_awards  do
      get :win_award_info
    end

    resources :awards do
      get :win_award_info
      collection do
        get :template
        post :save_template
      end
      member do
        get :change
      end
    end
    resources :posts do
      collection do
        get :bbs, :see_more

      end
      member do
        get :bbs_detail,:star
      end
      resources :replies do
        collection do
          get :see_more
        end
        member do
          get :verifyt,:verifyf,:verify
        end
      end
    end
    
    resources :resources
    resources :pages do
      resources :form_datas
      collection do
        get :sub, :form, :style, :sub_new,  :form_new ,:tmlt_sub_new,:change
        post :preview, :save_template3,:tmlt_sub_create,:zdy_sub_create
      end
      member do
        get :sub_edit,:form_edit, :if_authenticate, :sub_preview ,:tmlt_sub_edit
        post :submit_queries,:tmlt_sub_update
      end
    end
    
    resources :forms do
      member do
        get :submit_redirect
      end
    end

    resources :image_streams do
      #对集合进行操作
      collection do
        get :img_stream
      end
      #对单个进行操作
      member do
        get :edit_itpage,:change
      end
    end
    resources :image_texts do
      collection do
        post :preview
      end
      member do
        put :it_preview
        get :change
      end
    end
    resources :reminds do
      collection do
        post :create_records,:message_record
      end
      member do
      end
    end
  end
  match "/weixins/accept_token" => "weixins#accept_token"

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  devise_scope :user do
    root to: "devise/sessions#new"
  end

  # See how all your routes lay out with "rake routes"


  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
  # match '/:path_name',:to => "pages#static", :path_name => /\w+\/.+\.html/
end

app/controllers/forms_controller.rb
#encoding: utf-8
class FormsController < ApplicationController
  skip_before_filter :authenticate_user!, :only => [:submit_redirect]
  layout 'sites'
  before_filter :get_site, :except => [:submit_redirect]
  before_filter :resources_for_select, :only => [:new, :edit]
  def index
    @forms = @site.pages.form.includes(:form_datas).order("created_at desc").paginate(:page=>params[:page],:per_page=>10)
  end

  def new
    @form = Page.new
    @sub_pages = @site.pages.sub
  end

  def create
    labels = params[:labels]
    options = params[:options]
    params[:page][:file_name] = params[:page][:file_name] + ".html" if params[:page][:file_name]
    params[:page][:element_relation] = labels if labels
    
    Page.transaction do
      @form = @site.pages.create(params[:page])
      if @form.save
        submit_redirect = @form.submit_redirect.create(params[:tishi])
        redirect_path = submit_redirect_site_form_url(@site, @form)
        content = combine_form_html(@form, labels, options , @site, redirect_path)
        save_into_file(content, @form, "") if content
        flash[:notice] = "新建成功!"
        @path = redirect_path(@form, @site)
        render :success
      else
        @notice = "新建失败！ #{@form.errors.messages.values.flatten.join("\\n")}"
        render :fail
      end
    end
  end

  def edit
    @form = Page.find_by_id params[:id]
    @sub_pages = @site.pages.sub
    @submit_redirect = @form.submit_redirect[0]
    render :new
  end

  def update
    labels = params[:labels]
    labels_param = labels.dup
    options = params[:options]
    params[:page][:file_name] = params[:page][:file_name] + ".html" if params[:page][:file_name]
    params[:page][:element_relation] = labels_param if labels
    @form = Page.find_by_id params[:id]
    Page.transaction do
      params[:page][:element_relation].delete_if{|k,v| k.include?("text")}
      if @form.update_attributes(params[:page])
        if @form.submit_redirect[0]
          submit_redirect = @form.submit_redirect[0].update_attributes(params[:tishi])
        else
          submit_redirect = @form.submit_redirect.create(params[:tishi])
        end
        redirect_path = submit_redirect_site_form_url(@site, @form)
        content = combine_form_html(@form, labels, options , @site, redirect_path)
        save_into_file(content, @form, "") if content
        flash[:notice] = "更新成功!"
        @path = redirect_path(@form, @site)
        render :success
      else
        @notice = "更新失败！ #{@form.errors.messages.values.flatten.join("\\n")}"
        render :fail
      end
    end
  end

  def submit_redirect
    @site = Site.find_by_id params[:site_id]
    @form = Page.find_by_id(params[:id])
    @submit_redirect = @form.submit_redirect[0]
    render :layout => false
  end


  private

  def combine_form_html(page, labels, options , site, redirect_path)
    form_ele = ''
    labels.each do |name, value|
      name_str = name.to_s
      if name_str.include?("input")
        form_ele << "<div class='options'><li><label>#{value}</label><input name=\"form[#{name}]\" class='questionTitle' type=\"text\"></li></div>"
      elsif name_str.include?("radio")
        form_ele << "<h2>#{value}</h2><div class='options options2'>"
        options[name].each do |option|
          form_ele << "<li><input name=\"form[#{name}]\" class='questionTitle' type=\"radio\" value=\"#{option}\"><p>#{option}</p></li>"
        end
        form_ele << "</div>"
      elsif name_str.include?("checkbox")
        form_ele << "<h2>#{value}</h2><div class='options options2'>"
        options[name].each do |option|
           if option == "其他"
              form_ele << "<li><input class='questionTitle' type=\"checkbox\"><p>#{option} <input name=\"form[#{name}][]\" type=\"text\" style='width:150px'></p></li>"
           else
             form_ele << "<li><input name=\"form[#{name}][]\" class='questionTitle' type=\"checkbox\" value=\"#{option}\"><p>#{option}</p></li>"
           end
        end
        form_ele << "</div>"
      elsif name_str.include?("select")
        form_ele << "<h2>#{value}</h2><div class='options'>"
        form_ele << "<li><select name=\"form[#{name}]\" class='questionTitle'>"
        options[name].each do |option|
          form_ele << "<option>#{option}</option>"
        end
        form_ele << "</select></li></div>"
      elsif name_str.include?("text")
        form_ele << "<div class='options'><li><label>#{value}</label></li></div>"
      end
    end
    model_html = "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">
<html xmlns=\"http://www.w3.org/1999/xhtml\">
<head>
<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />
<meta name='viewport' content='width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no'>
                    <link href='/allsites/style/template_style.css' media='all' rel='stylesheet' type='text/css'></link>
                    <script src='/allsites/js/jQuery-v1.9.0.js' type='text/javascript'></script>
                  <script src='/allsites/js/form.js' type='text/javascript'></script>
                  <script src=\"/allsites/js/template_main.js\" type=\"text/javascript\"></script>
                    <title>preview</title>
                  </head>
                  <body>
                      <article>
                         <img src='#{ page.img_path}' width='100%'/>
                         <form accept-charset='UTF-8' action='/sites/#{site.id}/pages/#{page.id}/submit_queries' class='submit_form_static' method='post' data-redirect_path='#{redirect_path}'>
                             <div style=\"margin:0;padding:0;display:inline\">
                            <input name=\"utf8\" type=\"hidden\" value=\"✓\">
                            <input class='authenticity_token' name=\"authenticity_token\" type=\"hidden\" value=''></div>
                           <section class=\"form_list\">
                                <ul>" + form_ele +"</ul>
                                <div class=\"form_btn\"><button type='button' onclick=\"return submit_form(this)\">确认提交</button></div>
                           </section>
                         </form>

                          <div class='second_box' id='form_view'>
                            <div class='second_content second_content_3'>
                             <span class='second_dtl' id='the_content'></span>
                             <div class='second_box_act' id='form_view_btn'>
                              <a href='' ><span class='r_sure' >确认</span></a>
                             </div>
                            </div>
                           </div>
                      </article>
                  
                  <script language='javascript' type='text/javascript'>
                          $.ajax({
                              url: '/get_token',
                              type: 'get',
                              dataType: 'text',
                              success:function(data){
                                  var a = $('.authenticity_token');
                                  a.each(function(){
                                    $(this).val(data);
                                  });
                              },
                              error:function(data){
                              }
                          })
                  </script>
               </body>
          </html>"
    #TODO正则中文有问题
    model_html = model_html.gsub(/<title>.*<\/title>/, "<title>#{page.title}</title>")
    model_html
  end

  
end

app/views/forms/_pop_form_ele.html.erb
<div class="second_box addItem addTxtItem">
  <div class="second_content">
    <span class="close" >关闭</span>
    <h1>增加信息栏</h1>
    <div id="input_pop">
      <div class="insetBox">
        <div><label>信息栏名称：</label><input type="text" /></div>
      </div>
      <div class="scdBox_act">
        <button class="blue_btn addItemInput" >确认</button>
        <button class="blue_btn cancel">取消</button>
      </div>
    </div>
  </div>
</div>
<div class="second_box addItem addRdoItem">
  <div class="second_content">
    <span class="close" >关闭</span>
    <h1>增加单选框</h1>
    <div id="radio_pop">
      <div class="insetBox">
        <div class="label"><label>单选框问题：</label><input type="text" /></div>
        <div class="optBox"><label>单选框选项：</label><input type="text" /><span class="close2"></span></div>
        <div class="optBox"><label>单选框选项：</label><input type="text" /><span class="close2"></span></div>
        <div class="optBox"><label>单选框选项：</label><input type="text" /><span class="close2"></span></div>
      </div>
      <div class="scdBox_act">
        <button class="blue_btn addOptBox">增加选项</button>
        <button class="blue_btn addItemRC">确认</button>
        <button class="blue_btn cancel">取消</button>
      </div>
    </div>
  </div>
</div>
<div class="second_box addItem addChekItem">
  <div class="second_content">
    <span class="close">关闭</span>
    <h1>增加复选框</h1>
    <div id="checkbox_pop">
      <div class="insetBox">
        <div class="label"><label>复选框问题：</label><input type="text" /></div>
        <div class="optBox"><label>复选框选项：</label><input type="text" /><span class="close2"></span></div>
        <div class="optBox"><label>复选框选项：</label><input type="text" /><span class="close2"></span></div>
        <div class="optBox"><label>复选框选项：</label><input type="text" /><span class="close2"></span></div>
      </div>
      <div class="scdBox_act">
        <p style="margin-bottom: 10px;">
          <button class="blue_btn addOptBox">增加选项</button>
          <button class="blue_btn addOthBox">增加可输入选项</button>
        </p>
        <p>
          <button class="blue_btn addItemRC">确认</button>
          <button class="blue_btn cancel">取消</button>
        </p>
      </div>
    </div>
  </div>
</div>
<div class="second_box addItem addSelItem">
  <div class="second_content">
    <span class="close">关闭</span>
    <h1>增加下拉框</h1>
    <div id="select_pop">
      <div class="insetBox">
        <div class="label"><label>下拉框问题：</label><input type="text" /></div>
        <div class="optBox"><label>下拉框选项：</label><input type="text" /><span class="close2"></span></div>
        <div class="optBox"><label>下拉框选项：</label><input type="text" /><span class="close2"></span></div>
        <div class="optBox"><label>下拉框选项：</label><input type="text" /><span class="close2"></span></div>
      </div>
      <div class="scdBox_act">
        <button class="blue_btn addOptBox">增加选项</button>
        <button class="blue_btn addItemSelect">确认</button>
        <button class="blue_btn cancel">取消</button>
      </div>
    </div>
  </div>
</div>

<div class="second_box addItem addTxtItem2">
  <div class="second_content">
    <span class="close" >关闭</span>
    <h1>增加纯文本</h1>
    <div id="text_pop">
      <div class="insetBox">
        <div><label>增加纯文本：</label><input type="text" /></div>
      </div>
      <div class="scdBox_act">
        <button class="blue_btn addItemText">确认</button>
        <button class="blue_btn cancel">取消</button>
      </div>
    </div>
  </div>
</div>

<div class="second_box addSuccess">
  <div class="second_content">
    <span class="close" >关闭</span>
    <h1>提交成功页面</h1>
    <div id="after_submit_form">
      <div><label>提示信息：</label><input class="tishi_message"type="text" value="<%= @submit_redirect.present? ? @submit_redirect.message : ""  %>" /><span class="check">*</span></div>
      <div><label>电话：</label><input class="telephone"type="text" value="<%= @submit_redirect.present? ? @submit_redirect.phone : ""  %>"/></div>
      <div><label>地址：</label><input class="address" type="text" value="<%= @submit_redirect.present? ? @submit_redirect.address : ""  %>"/></div>
      <div class="scdBox_act">
        <button class="blue_btn confirm_after_aubmit">确认</button>
        <button class="blue_btn cancel">取消</button>
      </div>
    </div>
  </div>
</div>

app/views/forms/fail.js.erb
<% if @form.errors.any? %>
  tishi_alert("<%= @notice.html_safe() %>")
<% end %>

app/views/forms/index.html.erb
<div class="main_container">
  <%= render '/shared/left_panel' %>
  <div class="main_cont">
    <%= render '/shared/page_title' %>

    <div class="tabDiv">
      <div class="page_content">
        <div class="page_tit">
          <%= link_to "新建表单", new_site_form_path(@site),:class => "blue_btn scd_btn" %>
        </div>
        <div class="page_txt">
          <table class="table1">
            <tr>
              <th width="80">标题</th>
              <th width="280">路径</th>
              <th width="50">访问权限</th>
              <th width="350">操作</th>
            </tr>
            <% @forms.each do |page| %>
              <tr id="<%= page.id %>">
                <td class="title"><%= page.title %></td>
                <td class="path"><%= "/sites/static" + "?path_name=" + page.path_name %></td>
                <td class="authenticate"><%= if_authenticate(page)%></td>
                <td>
                  <%= link_to "访问权限" , if_authenticate_site_page_path(@site,page),:remote => true, :class => "blue_btn"%>
                  <%= link_to "编辑" , edit_site_form_path(@site,page), :class => "blue_btn"%>
                  <%= link_to "删除" , site_page_path(@site, page),:method => :delete, :confirm => "确定删除吗？", :class => "blue_btn"%>
                  <%= link_to "预览" , "/sites/static" + "?path_name=" + page.path_name,:target =>"_blank", :class => "blue_btn page_preview" %>
                  <% if  page.form_datas.length != 0 %>
                    <%= link_to "下载数据", site_page_form_datas_path(@site,page, :format => 'xls'), :class => "blue_btn" %>
                  <% else %>
                    <%= link_to "下载数据", "#", :class => "blue_btn", :onclick => "tishi_alert('暂无数据')" %>
                  <% end %>
                  <span> <%= page.form_datas.length %>条数据</span>
                </td>
              </tr>
            <% end %>
          </table>
        </div>
        <div class="clear"></div>
        <div class="digg_pagination" style="margin:0 auto;text-align: center;">
          <%= will_paginate  @forms,:previous_label=>'上一页',:next_label=>'下一页'%>
        </div>

        <div class="page_act"></div>
      </div>
    </div>
  </div>
</div>

app/views/forms/new.html.erb
<div class="main_container">
  <%= render '/shared/left_panel' %>
  <div class="main_cont">
    <%= form_for @form, :url => @form.new_record? ? "/sites/#{@site.id}/forms" : "/sites/#{@site.id}/forms/#{@form.id}", :method => @form.new_record? ? :post : :put do |f| %>
      <div class="tit"><span>标题：</span>
        <%= f.text_field :title %>
        <span>文件名：</span>
        <%= f.text_field :file_name, :value => @form.new_record? ? "" : @form.file_name.gsub(".html", "") %><span>.html</span></div>
      <%= f.hidden_field :types, :value => Page::TYPE_NAMES[:form] %>
      <hr class="cf" color="#bcbcbc" />
      <div class="vstContr">
        <span>访问控制：</span>
        <div class="vcItem <%= @form && @form.authenticate ? "check" : "" %>"><%= radio_button "form", "authenticate", 1, :checked => @form && @form.authenticate ? true : false %><span>是</span></div>
        <div class="vcItem <%= @form && @form.authenticate ? "" : "check" %>"><%= radio_button "form", "authenticate", 0, :checked => @form && @form.authenticate ? false : true %><span>否</span></div>
      </div>
      <div class="formAct">
        <button class="blue_btn scd_btn" type="button" data-ele="input_pop">增加信息栏</button>
        <button class="blue_btn scd_btn" type="button" data-ele="radio_pop">增加单选框</button>
        <button class="blue_btn scd_btn" type="button" data-ele="checkbox_pop">增加复选框</button>
        <button class="blue_btn scd_btn" type="button" data-ele="select_pop">增加下拉框</button>
        <button class="blue_btn scd_btn" type="button" data-ele="text_pop">增加纯文本</button>
        <button class="blue_btn scd_btn" type="button" data-ele="after_submit_form" style="padding: 8px 19px;">添加提交成功页</button>
      </div>
      <div class="iphoneVirtual">
        <div class="topPic"><img src="<%= @form && @form.img_path ? @form.img_path : '' %>" width="320" height="150"/></div>
        <%= f.hidden_field :img_path, :value => @form && @form.img_path ? @form.img_path : "" %>
        <div class="form_ele">
          <% if !@form.new_record? && @form.page_html %>
            <%= raw @form.page_html %>
          <% end %>
        </div>
        <textarea style="display:none" class="hidden_html" name="page[page_html]" ></textarea>
      </div>
      <!-- 表单提交跳转页-->
      <div class="hidden_after_submit_info">
        <input type="hidden" name="tishi[message]" class = "message" value="<%= @form.new_record? ? "" : @form.submit_redirect[0].try(:message) %>"/>
        <input type="hidden" name="tishi[phone]" class = "phone" value="<%= @form.new_record? ? "" : @form.submit_redirect[0].try(:phone) %>"/>
        <input type="hidden" name="tishi[address]" class = "address" value="<%= @form.new_record? ? "" : @form.submit_redirect[0].try(:address) %>"/>
      </div>
      <div id="tupian">
        <%= render 'shared/form_images',:objects => @imgs_path %>
      </div>
      <div class="pageAct">
        <button class="blue_btn" type="button" onclick="submit_form_page(this, '<%= @site.id %>')">保存</button>
  <%#= link_to "预览" , "/sites/static" + "?path_name=" + @page.path_name,:target =>"_blank", :class => "blue_btn page_preview" %>
      </div>
    <% end %>
  </div>
</div>
<div id="viewLarge"></div>
<!--弹出框 页面代码-->
<%= render "pop_form_ele" %>

<script type="text/javascript">
  $input_320 = $( ".topPic" );
  // drop 元素
  form_it_drop($input_320, 320, 150);

  var img = $(".topPic").find("img");
  setImageWH(img, 320, 150)

</script>

app/views/forms/submit_redirect.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    <title><%= @form.title %></title>
    <script type="text/javascript" src="/allsites/js/jQuery-v1.9.0.js"></script>
    <link href="/allsites/style/template_style.css" rel="stylesheet" type="text/css"/>
  </head>

  <body>
  <article style="margin-bottom: 50px">
    <section class="transit_text">
      <p><%= @submit_redirect.message %></p>
    </section>
    <section class="key">
      <ul>
        <% if @submit_redirect.address.present? %>
          <li><a href="http://api.map.baidu.com/geocoder?address=' + <%= @submit_redirect.address %> + '&output=html" class="adress"><span class="adress_icon"><%= @submit_redirect.address %></span></a></li>
        <% end %>
        <% if @submit_redirect.phone.present? %>
          <li><a href="tel:<%= @submit_redirect.phone %>" class="phone"><span class="phone_icon"><%= @submit_redirect.phone %></span></a></li>
        <% end %>
      </ul>
    </section>
  </article>
  <%= raw page_footer(@site) %>
</body>
<script type="text/javascript" src="/allsites/js/template_main.js"></script>
</html>

app/views/forms/success.js.erb
window.location.replace("<%= @path %>")